### ISSUE TITLE
Is it possible to get is image

### ISSUE THREAD

**Issue by redimongo** [jshttp/mime-types#102]
So I currently am doing the following to work out if a file is an image or not.

```
var extension = mime.extension(req.file.mimetype);
if(extension == "png" || extension == "gif" || extension == "jpeg" || extension == "jpg")
          {
            res.status(200).error({code:500, message: "Error with file type"});
          }
```

However the issue is that unless I put every file extension that is an image which lets be real, there is a lot of different formats I could miss one, it would be great to see a way that we can give the file.mimetype and it return things like: image, audio, executable, html, other.

Not sure if anyone else things this could be good.

Side topic: We noticed that mpegs end up getting `mpga` instead of `.mp3`

**Comment by dougwilson** [comment]
This module doesn't keep a list of everything that is or is not an image and that is out of scope for this module (could be a good module to make!). If you wanted, you could _assume_ that if the mime type for an extension starts with `image/` then it is an image, and that's the most you'll be able to do with this module, unfortunately.

But since you already have the mime as `req.file.mimetype` then you don't need to use this module to perform that check.

**Comment by dougwilson** [comment]
```js
if(!req.file.mimetype.startWith("image/"))
          {
            res.status(200).error({code:500, message: "Error with file type"});
          }

```
