### ISSUE TITLE
Drop outdated node platforms from CI test matrix

### ISSUE THREAD

**Issue by broofa** [jshttp/mime-types#115]
The current CI test matrix goes all the way back to node@0.6.  This seems "excessive". 
Over at the `uuid` project, we limit our test matrix to "node LTS plus one previous version".  E.g. with node LTS now at v18, I expect we'll to drop support for pre-v16 versions with our next major release.

This has worked well for years, and has not caused any issues with our users.  Users that want legacy platform support just pin their dependency to a prior version of `uuid`.

I'd like to propose `mime-types` do the same.  This will make contributing code simpler.

**Comment by dougwilson** [comment]
For sure, this module will be dumping lots of versions. The exact ones will most likely be matched up to what express 5 needs, since this module is used there and maintained by the express project so it can be compatible, haha.

**Comment by riderx** [comment]
I just arrived here because I try to use `minio` in Cloudflare worker and this package is a sub dependency of it.
Currently, I cannot deploy because Node.js compat of Cloudflare enforces the `node:` prefix for Node.js deps.
![CleanShot 2024-02-13 at 00 08 48@2x](https://github.com/jshttp/mime-types/assets/4084527/56dc41e1-d954-4cc5-98ed-7804cd0d95e3)
Switching to Node.js min version would allow this to be switched since the prefix has been implemented in 16 and backport up to 12 !
Will create a Pr in that direction.

**Comment by dougwilson** [comment]
It is unlikely we will drop that many versions, I need the versions still without node prefix support and I maintain the module, so it would make no sense for me to make the module unsable to it's own maintainer.

Perhaps if you need that you can either transpile the code or use `mime` module.

I'm going to close this issue since it is unnecessary to keep it open, as it will be addressed to whatever the Express.js minimum gets bumped to.
