### ISSUE TITLE
Mime Type : image/jpg Not working

### ISSUE THREAD

**Issue by incredible-dev** [jshttp/mime-types#24]
I have tried

  `console.log(mime.extension('image/jpg'));`

I get `false` , please let me know the correct way to get jpg in the above case.

**Comment by hacksparrow** [comment]
The valid mine type is "image/jpeg".

**Comment by dougwilson** [comment]
Exactly, you're getting `false` back because there is no such MIME as `"image/jpg"` in our discionary, especially since the MIME for jpg files is `"image/jpeg"` like @hacksparrow said :)

**Comment by HardlyMirage** [comment]
Shouldn't `mime.extension('image/jpeg')` return `jpg` and not `jpeg`?

**Comment by hacksparrow** [comment]
@HardlyMirage nah, `image/jpeg` is the correct value. 

`.jpg` is just an acceptable file name extension of the mime-type `image/jpeg`.

**Comment by HardlyMirage** [comment]
@hacksparrow I mean, the extension should be `jpg` instead of `jpeg` as the 3-letter one is more commonly used.

**Comment by hacksparrow** [comment]
The [MIME type](https://en.wikipedia.org/wiki/Media_type) values were decided by [IANA](https://en.wikipedia.org/wiki/Internet_Assigned_Numbers_Authority) a long time ago. So even if `jpg` is more popular and feels more "natural", we can't do anything about it. That's how Internet protocols work.

**Comment by HardlyMirage** [comment]
Got it! Interestingly, image/jpeg is not listed here:
http://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by hacksparrow** [comment]
No idea why they left the entry blank for `jpeg`, but you will find the reference here - http://tools.ietf.org/html/rfc2046.

**Comment by dougwilson** [comment]
Hi @HardlyMirage, I think you may just be confused on how http://www.iana.org/assignments/media-types/media-types.xhtml lists the types :) The column you are looking at is called "Template", which is not always the actual MIME type. You have to form the MIME type in that list by going to the section, which is the type, and the "Name" column corresponds to the subtype. MIME type are written as `{type}/{subtype}`, thus to find `image/jpeg`, you would look in the `image` section for the row with the Name column `jpeg`. This happens to be the 8th row currently.

**Comment by dougwilson** [comment]
As for how this module decides to map `image/jpeg` to `.jpeg`, it actually uses the `mime-db` module (found at https://github.com/jshttp/mime-db), which contains an aggregation of data sources from IANA, the Apache HTTPD project, and Nginx.

The particular `.jpeg` preference comes from the Apache feed http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types

The problem with these types of things is that when a type has multiple extensions, it can sometimes be way too opinionated on which one is the "right" one. We actually feel like staying out of those debates and instead rely on feeds from very well-established projects to make & discuss those decisions.

That said, you can of course override the definitions for this module, for example, you can do `mime.extensions['image/jpeg'].unshift('jpg')` if you prefer to see `.jpg` as the main extension. For a more full-features library with APIs for defining your types, you may also want to check out https://www.npmjs.com/package/mime

In the future, @HardlyMirage, you are always welcome to open a new issue instead of hijacking an old, unrelated issue. This issue was about the topic that the type `image/jpg` is not working (see the issue title and the initial post), which you question was not in relation to (it was regarding `image/jpeg` returning `jpeg`).
