### ISSUE TITLE
Change API to return null or undefined and not false

### ISSUE THREAD

**Issue by andys8** [jshttp/mime-types#54]
In cases where the input is wrong or the result can not be provided, the current API returns `false`. Therefore the type signature returns this mix of `string` and `boolean`.
https://github.com/jshttp/mime-types/blob/master/index.js#L143

The more consistent and expected behaviour would be to consider "nullable types" (see http://www.typescriptlang.org/docs/handbook/advanced-types.html) and return either `undefined` or `null` with the resulting `string` being optional. In case the input is wrong or missing (the user makes a mistake) one could also consider to throw an error to fail early.

Is there a specific reason the API is designed as it is? Is it possible to bump major version and fix the signature regarding the amount of users?

**Comment by dougwilson** [comment]
Hi @andys8 yea, I can see what you mean, though the link to TypeScript doesn't really matter here in general, as this is a JavaScript library, not a TypeScript library.

> Is there a specific reason the API is designed as it is?

I don't think anyone is around these days from when this API decision was made, and I don't know exactly, so I unfortunately cannot provide you insight into that. Looking at the `git` history, the API of returning `false` is there since the very first commit: 1da5f79cd74fcb5763eba6b98d45286764f6768c

> Is it possible to bump major version and fix the signature regarding the amount of users?

It's possible, though unless there is a really good reason and someone is going to volunteer to pick up the torch and make pull requests and inform the community of this change, it seems too large to do at this point. The API of this module is just meant to mimic `mime@1.x` as a drop-in, especially now that `mime` released 2.x with a completely different API.

1,262 public npm modules depend on the existing behavior and the constant updates to the mime database. Releasing a new major will immediately cut all those users off from further database updates until every module gets updated. I'm not sure how easy it will be to update with this type of API change, since it's a subtle change in the return value vs something like a function being removed.

Perhaps if someone can estimate what the usage of this API is out there we can form a conversation around the impact of the change, as otherwise, like it or not (I don't like the API), it's just now "part of the ecosystem" and not an easy rock to move.

**Comment by dougwilson** [comment]
Closing due to no follow up response to continue discussion.

**Comment by andys8** [comment]
I think the current api is not the best it could be, but popular public apis are very hard to change. Comparing the benefit and the potential damage due to breaking the API, I'm fine with closing the issue.
