### ISSUE TITLE
Missing "jfif" extension mime type

### ISSUE THREAD

**Issue by GustavoMilitao** [jshttp/mime-types#68]
When I use lookup("jfif"), the result is false because it haven't "jfif" in exports.types[extension]. "jfif" is an image extension. See the link below.

https://www.w3.org/Graphics/JPEG

**Comment by dougwilson** [comment]
The lookup is just for file extensions. I don't see anything on that page that says there is a file extension of ".jfif" unless I'm missing something there. Can you highlight where on that page it lists a file extension?

**Comment by GustavoMilitao** [comment]
"JPEG JFIF, which is what people generally mean when they refer to "JPEG", is a file format created by the Independent JPEG Group (IJG) for the transport of single JPEG-compressed images."

When I save images using Windows 10, jfif extension is selected by default.

**Comment by dougwilson** [comment]
So instead of continuing conversation here, you may want to open an issue where the actual data comes from. You can see in our github source code that this module doesn't actually include extension data, so it's not something that would be directly fixed here.

If you think otherwise, please share what changes you think this module should make to address your concern and they can be made. The underlying data is pulled from the IANA, so if they don't include that file extension, it won't be available in this module, either. So the source database would be what needs correcting. This module is just an API to that.

**Comment by JayeshLadumor** [comment]
@GustavoMilitao This issue is happening due to "jfif" extension is not part of mime-db. As this library internally uses mime-db to get all the file types and extensions.
